# Generated by Django 2.1.7 on 2019-03-07 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190306_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_group',
            name='active',
        ),
    ]
