# Generated by Django 2.1.5 on 2019-03-21 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190320_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student_group',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_group_id', to='api.Group'),
        ),
        migrations.AlterField(
            model_name='student_group',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_group_id', to='api.Student'),
        ),
    ]
